# Generated by Django 5.1.4 on 2025-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitgliedsantrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('geburtsdatum', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mitgliedsantrag',
                'verbose_name_plural': 'Mitgliedsanträge',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
