# Generated by Django 5.1.4 on 2025-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitgliedsantrag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitgliedsantrag',
            options={},
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='geburtsdatum',
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='nachname',
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='mitgliedsantrag',
            name='vorname',
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='beitrag',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Monatlicher Beitrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='bic',
            field=models.CharField(default=10, max_length=11, verbose_name='BIC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='iban',
            field=models.CharField(default=1, max_length=34, verbose_name='IBAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='kontoinhaber',
            field=models.CharField(default=1, max_length=255, verbose_name='Kontoinhaber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='mobilnummer',
            field=models.CharField(default=1, max_length=20, verbose_name='Mobilnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name und Vorname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='pdf_datei',
            field=models.FileField(default=1, upload_to='mitgliedsantrag/pdfs/', verbose_name='PDF-Datei'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='unterschrift',
            field=models.ImageField(default=1, upload_to='mitgliedsantrag/signaturen/', verbose_name='Unterschrift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='zahlungstermin',
            field=models.CharField(choices=[('1.', '1. des Monats'), ('15.', '15. des Monats')], default='1.', max_length=10, verbose_name='Zahlungstermin'),
        ),
        migrations.AlterField(
            model_name='mitgliedsantrag',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='mitgliedsantrag',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
    ]
