# Generated by Django 5.1.4 on 2025-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitgliedsantrag', '0002_alter_mitgliedsantrag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitgliedsantrag',
            name='unterschrift',
            field=models.ImageField(blank=True, null=True, upload_to='mitgliedsantrag/signaturen/', verbose_name='Unterschrift'),
        ),
    ]
