# Generated by Django 5.1.4 on 2025-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitgliedsantrag', '0004_mitgliedsantrag_unterschrift2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitgliedsantrag',
            name='bearbeitet',
            field=models.BooleanField(default=False),
        ),
    ]
