# Generated by Django 5.1.4 on 2025-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moscheefuehrung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einrichtung', models.CharField(max_length=200, verbose_name='Name der Einrichtung / Schule')),
                ('ansprechperson', models.CharField(max_length=100, verbose_name='Ansprechperson')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('teilnehmerzahl', models.PositiveIntegerField(verbose_name='Anzahl der Teilnehmer')),
                ('wunschtermin', models.DateField(verbose_name='Wunschtermin')),
                ('uhrzeit', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht / Anliegen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
