# Generated by Django 5.1.4 on 2025-05-04 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuehrung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moscheefuehrung',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Bitte eine gültige Telefonnummer eingeben (nur Ziffern, +, (), - und Leerzeichen erlaubt).', regex='^[0-9+() -]+$')], verbose_name='Telefonnummer'),
        ),
    ]
