# Generated by Django 5.1.4 on 2025-05-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuehrung', '0002_alter_moscheefuehrung_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='moscheefuehrung',
            name='bearbeitet',
            field=models.BooleanField(default=False),
        ),
    ]
