# Generated by Django 5.1.4 on 2025-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='downloads/')),
            ],
        ),
    ]
