# Generated by Django 5.1.4 on 2025-04-26 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neuigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('inhalt', models.TextField()),
                ('bild', models.ImageField(blank=True, null=True, upload_to='neuigkeiten_bilder/')),
                ('erstellt_am', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
