# Generated by Django 5.1.4 on 2025-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptseite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktNachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nachricht', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
