# Generated by Django 5.1.4 on 2025-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauptseite', '0002_kontaktnachricht'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktnachricht',
            name='bearbeitet',
            field=models.BooleanField(default=False),
        ),
    ]
